#  Welcome to extra resources

In this notebook will show some intermidiate code concepts.

<br>

## Table of content:
1. Indentation and break lines
1. String format
1. List advanced operations
1. List comprehension
1. Sorting Dictionaries
1. Dictionary comprehension
1. Lambda function
1. Map
1. Filter
1. Reduce
1. Enumerate
1. Zip
1. Escape Characters
1. Text files

### Indentation

Indentation is used to indicate the grouping of statements. It specifies which statements belong together in a block of code. The standard indentation in Python is four spaces.

When breaking a long statement into multiple lines, the backslash character (`\`) can be used to continue the statement on the next line. The backslash character tells Python that the statement is continued on the next line, and the indentation of the next line should be consistent with the previous line.

<br>

```python
  fruits = ['apple', 'banana', 'orange', 'grape', 'watermelon',\
            'pineapple', 'mango']
```

<br>

### Code examples

In [ ]:
def add_numbers(x, y, z):
    result = x + \
             y + \
             z
    return result

add_numbers(1,2,3)

6

In [ ]:
def calculate_total_price(product_prices):
    total_price = 0
    for product, price in product_prices.items():
        if product == 'apple':
            total_price += price \
                * 1.1  # add 10% for apple
        elif product == 'orange':
            total_price += price \
                * 1.2  # add 20% for orange
        elif product == 'banana':
            total_price += price \
                * 1.3  # add 30% for banana
        else:
            print('Unknown product:', product)
    return total_price

item_dict = {'apple': 10, 'orange': 20,}
calculate_total_price(item_dict)

35.0

___
### String Format

String formatting is a way to create a new formatted string by inserting values into placeholders in a string. There are several ways to format strings in Python, but the most common method is to use the format() method or f-strings (formatted string literals).

Using the format() method, you can create a string with placeholders (using curly braces {}) and then pass values to be inserted into those placeholders as arguments to the format() method. Here's an example:

<br>

```python
  name = "John"
  age = 30
  city = "New York"

  message = "My name is {}, I'm {} years old, and I live in {}.".format(name, age, city)

  print(message)

  [out] "My name is John, I'm 30 years old, and I live in New York."
```

> In this example, we created a string with three placeholders using curly braces {}. We then passed three variables (name, age, and city) as arguments to the format() method to replace the placeholders in the string with their values.

<br>

With f-strings, you can directly insert variables and expressions inside curly braces {} in a string literal. Here's an example:

```python
  name = "John"
  age = 30
  city = "New York"

  message = f"My name is {name}, I'm {age} years old, and I live in {city}."

  print(message)
  [out] "My name is John, I'm 30 years old, and I live in New York."
```

> In this example, we used an f-string to create a string literal with variables and expressions directly inserted into curly braces {}. The variables are evaluated and their values are inserted into the string.

<br>

### Code examples

String format()

In [ ]:
name = "John"
age = 25
print("My name is {} and I am {} years old.".format(name, age))

My name is John and I am 25 years old.

In [ ]:
print("My name is {1} and I am {0} years old.".format(age, name))

My name is John and I am 25 years old.

In [ ]:
print("I have a {fruit} and it costs {price:.2f} dollars.".format(fruit="banana", price=0.25))

I have a banana and it costs 0.25 dollars.

f-string

In [ ]:
name = "Alice"
age = 30
print(f"My name is {name} and I am {age} years old.")

My name is Alice and I am 30 years old.

In [ ]:
x = 5
y = 7
print(f"The sum of {x} and {y} is {x + y}.")

The sum of 5 and 7 is 12.

In [ ]:
person = {"name": "Alice", "age": 30}
print(f"My name is {person['name']} and I am {person['age']} years old.")

My name is Alice and I am 30 years old.

In [ ]:
person = ["Andrei", 30]
print(f"My name is {person[0]} and I am {person[1]} years old.")

My name is Andrei and I am 30 years old.

___
### List advanced operations

- Join string list
- Sum
- Max
- Min
- Mean

___
___
#### Join string list

The `join()` method can be used to join a list of strings into a single string. It takes a separator string as an argument and returns a new string that contains all the elements of the list separated by the specified separator.

<br>

```python
  my_list = ['Hello', 'world', 'how', 'are', 'you']
  str_separator = ' '
  result = str_separator.join(my_list)
  print(result)

  [out] "Hello world how are you."
```

<br>

#### Code examples

In [ ]:
my_list = ['1', '2', '3', '4', '5']
result = ",".join(my_list)
print(result)

1,2,3,4,5

In [ ]:
my_list = ['hi', 'hello', 'alo', 'hey']
result = "/".join(my_list)
print(result)

hi/hello/alo/hey

___
___
#### Sum

The `sum()` is a built-in function that returns the sum of a sequence of numbers. It takes an iterable (e.g. list, tuple, set) as an argument and returns the sum of all the elements in the iterable.

<br>

```python
  numbers = [1, 2, 3, 4, 5]
  total = sum(numbers)
  print(total)

  [out] 15
```

<br>

#### Code examples

In [ ]:
numbers = [100, 500, 1000, 1500, 2000]
total = sum(numbers)
print(total)

5100

In [ ]:
numbers = [1.5, 0.33, 15.7, 25]
total = sum(numbers)
print(total)

42.53

___
___
#### Max

The `max()` function returns the largest item in an iterable (e.g. list, tuple, set, etc.) or the largest of two or more arguments.

<br>

```python
  my_list = [3, 7, 2, 10, 5]
  largest = max(my_list)
  print(largest)

  [out] 10
```

<br>

#### Code examples

In [ ]:
my_list = [151, 584, 1021, 587, 5205, 1]
largest = max(my_list)
print(largest)

5205

In [ ]:
my_list = [[151, 584],[ 1021, 587], [5205, 1], [5000, 5001]]
largest = max(my_list)
print(largest)

[5205, 1]

___
___
#### Min

The `min()` function returns the smallest item in an iterable or the smallest of two or more arguments.

<br>

```python
  my_list = [3, 7, 2, 10, 5]
  smallest = min(my_list)
  print(smallest)

  [out] 2
```

<br>

#### Code examples

In [ ]:
my_list = [151, 584, 1021, 587, 5205, 1]
smallest = min(my_list)
print(smallest)

1

In [ ]:
my_list = [[151, 584], [1021, 587], [5205, 1], [5000, 5001]]
smallest = min(my_list)
print(smallest)

[151, 584]

___
___
#### Mean

The mean (average) of a list can be calculated by summing up all the elements in the list and then dividing the sum by the length of the list.

<br>

```python
  my_list = [3, 7, 2, 10, 5]
  mean = sum(my_list) / len(my_list)
  print(mean)

  [out] 5.4
```

<br>

#### Code examples

In [ ]:
grades = [10, 10, 8, 9 ,7.5]
mean = sum(grades) / len(grades)
print(mean)

8.9

___
___
#### Multiply

You can use the multiplication operator `*` to create a new list with repeated elements. When you multiply a list by an integer, it creates a new list that contains the original elements repeated by that number of times. 

<br>

```python
  my_list = [1, 2, 3]
  new_list = my_list * 3
  print(new_list)

  [out] [1, 2, 3, 1, 2, 3, 1, 2, 3]
```

<br>

#### Code examples

In [ ]:
my_list = [1]
new_list = my_list * 50
print(new_list)
print(len(new_list))

[1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1]
50

___
### List Comprehension

List comprehension is a concise way to create a new list by applying an expression to each element of an existing list (or other iterable), optionally filtering the elements based on a condition.

<br>

```python
  my_list = [1, 2, 3, 4, 5]
  new_list = []
  for x in my_list:
    new_list.append(x*2)
  print(new_list)

  [out] [2, 4, 6, 8, 10]


  my_list = [1, 2, 3, 4, 5]
  new_list = [x*2 for x in my_list]
  print(new_list)

  [out] [2, 4, 6, 8, 10]
```

<br>

### List Comprehension with conditionals

A list comprehension can include a conditional expression to filter the elements of the input list. The condition is placed after the expression and is evaluated for each element.

```python
  my_list = [1, 2, 3, 4, 5]
  new_list = [x for x in my_list if x % 2 == 0]
  print(new_list)

  [out] [2, 4]
```

> In this example, the list comprehension creates a new list that includes only the even numbers from the input list. The condition `if x % 2 == 0` is used to filter out the odd numbers.

<br>

### Code examples

Simple list comprehension

In [ ]:
# Convert numeric list into string list
str_numbers = [str(x) for x in range(11)]
print(str_numbers)

['0', '1', '2', '3', '4', '5', '6', '7', '8', '9', '10']

In [ ]:
# Generating a list of even numbers using list comprehension
even_numbers = [x*2 for x in range(11)]
print(even_numbers)

[0, 2, 4, 6, 8, 10, 12, 14, 16, 18, 20]

In [ ]:
# Generating a list of squares of numbers from 1 to 10 using list comprehension
squares = [x**2 for x in range(1, 11)]
print(squares)

[1, 4, 9, 16, 25, 36, 49, 64, 81, 100]

Conditional list comprehension

In [ ]:
# Generating a list of even numbers from 0 to 10 using list comprehension with conditional
even_numbers = [x if x % 2 == 0 else "NA" for x in range(11)]
print(even_numbers)

[0, 'NA', 2, 'NA', 4, 'NA', 6, 'NA', 8, 'NA', 10]

In [ ]:
# Generating a list of even numbers from 0 to 10 using list comprehension with conditional
even_numbers = [x if x % 2 == 0 else "NA" for x in range(11) if x % 2 == 0]
print(even_numbers)

[0, 2, 4, 6, 8, 10]

In [ ]:
# Generating a list of squares of even numbers from 1 to 10 using list comprehension with conditional
squares = [x**2 for x in range(1, 11) if x % 2 == 0]
print(squares)

[4, 16, 36, 64, 100]

In [ ]:
# Generating a list of words from a string with length greater than 3 and starting with letter "s" using list comprehension with conditional
string = "This is a sample string with some words"
words = [word for word in string.split() if len(word) > 3 and word[0] == "s"]
print(words)

['sample', 'string', 'some']

___
### Sorting Dictionaries

Dictionaries can be sorted by their keys or values. Sorting by keys can be done using the `sorted()` method, while sorting by values can be done using the `sorted()` method with a key parameter.

Ways of sorting:
- Key
- Value

<br>

#### By key

```python
  # Define a dictionary
  fruits = {"banana": 3, "apple": 2, "pear": 4, "orange": 1}

  # Sort by key
  sorted_fruits = dict(sorted(fruits.items()))

  print(sorted_fruits)

  [out] {'apple': 2, 'banana': 3, 'orange': 1, 'pear': 4}
```

<br>

#### By value

```python
  # Define a dictionary
  fruits = {"banana": 3, "apple": 2, "pear": 4, "orange": 1}

  # Sort by value
  sorted_fruits = dict(sorted(fruits.items(), key=lambda item: item[1]))

  print(sorted_fruits)

  [out] {'orange': 1, 'apple': 2, 'banana': 3, 'pear': 4}
```

<br>

### Code examples

Sorting by key

In [ ]:
# Define a dictionary
numbers = {5: "a", 7: "c", 1: "d", 10: "b", 4: "e"}

# Sort by key
sorted_numbers = dict(sorted(numbers.items()))

print(sorted_numbers)

{1: 'd', 4: 'e', 5: 'a', 7: 'c', 10: 'b'}

In [ ]:
# Define a dictionary
numbers = {5: "a", 7: "c", 1: "d", 10: "b", 4: "e"}

# Sort by key in descending order
sorted_numbers = dict(sorted(numbers.items(), reverse=True))

print(sorted_numbers)

{10: 'b', 7: 'c', 5: 'a', 4: 'e', 1: 'd'}

Sorting by value

In [ ]:
# Define a dictionary
numbers = {5: "a", 7: "c", 1: "d", 10: "b", 4: "e"}

# Sort by value
sorted_numbers = dict(sorted(numbers.items(), key=lambda item: item[1]))

print(sorted_numbers)

{5: 'a', 10: 'b', 7: 'c', 1: 'd', 4: 'e'}

In [ ]:
# Define a dictionary
numbers = {5: "a", 7: "c", 1: "d", 10: "b", 4: "e"}

# Sort by value in descending order
sorted_numbers = dict(sorted(numbers.items(), key=lambda item: item[1], reverse=True))

print(sorted_numbers)

{4: 'e', 1: 'd', 7: 'c', 10: 'b', 5: 'a'}

___
### Dictionary Comprehension

Dictionary comprehension is a concise way of creating a dictionary in Python by looping through an iterable object and returning a dictionary with key-value pairs. It follows a similar syntax as list comprehension, but instead of returning a list, it returns a dictionary.

<br>

```python
  squares = {num: num**2 for num in range(1, 6)}
  print(squares)

  [out] {1: 1, 2: 4, 3: 9, 4: 16, 5: 25}
```

<br>

### Dictionary Comprehension with conditionals

A dictionary comprehension can include a conditional expression to filter the elements of the input list. The condition is placed after the expression and is evaluated for each element.

```python
  even_squares = {num: num**2 for num in range(1, 6) if num % 2 == 0}
  print(even_squares)

  [out] {2: 4, 4: 16}
```

> In this example, the condition num % 2 == 0 filters out the odd numbers, and the resulting dictionary contains only even squares.

<br>

### Code examples

In [ ]:
# Create a dictionary of numbers using dictionary comprehension
numbers_dict = {num: str(num) for num in range(1, 11)}
print(numbers_dict)

{1: '1', 2: '2', 3: '3', 4: '4', 5: '5', 6: '6', 7: '7', 8: '8', 9: '9', 10: '10'}

In [ ]:
# Create a dictionary of even numbers up to 20 using dictionary comprehension
even_dict = {num: num for num in range(2, 21) if num % 2 == 0}
print(even_dict)

{2: 2, 4: 4, 6: 6, 8: 8, 10: 10, 12: 12, 14: 14, 16: 16, 18: 18, 20: 20}

In [ ]:
# Create a dictionary of vowels in a word along with their count using dictionary comprehension
word = "encyclopedia"
vowel_dict = {char: word.count(char) for char in word if char in 'aeiou'}
print(vowel_dict)

{'e': 2, 'o': 1, 'i': 1, 'a': 1}

In [ ]:
# Create a dictionary of grades where the keys are the student names and values are their grades, but only include students with a grade of 60 or above
grades = {'John': 70, 'Alice': 50, 'Bob': 80, 'Jane': 65}
passing_grades = {name: grade for name, grade in grades.items() if grade >= 60}
print(passing_grades)

{'John': 70, 'Bob': 80, 'Jane': 65}

___
### Lambda function

Lambda function, also known as anonymous function, is a small, single-expression function that can be defined without a name. It is used when you need a small function for a short period of time and don’t want to define a full function.

The general syntax of a lambda function is:

```python
lambda arguments: expression
```
Where:

- `arguments` are the input parameters of the function.
- `expression` is the output of the function, usually a single line of code.

<br>

#### Implementation

```python
  add = lambda x, y: x + y
  print(add(2, 3))

  [out] 5
```

<br>

### Code examples

In [ ]:
def add(x, y):
  return x + y

In [ ]:
is_even = lambda x: x % 2 == 0
print(is_even(4))
print(is_even(5))

True
False

In [ ]:
square = lambda x: x**2
print(square(4))

16

In [ ]:
list_of_tuples = [(1, 2), (4, 1), (3, 4), (2, 3)]
sorted_list = sorted(list_of_tuples, key=lambda x: x[1])
print(sorted_list)

[(4, 1), (1, 2), (2, 3), (3, 4)]

In [1]:
text = "HOLA"
text.lower()

'hola'

In [2]:
text.lower

In [14]:
def prueba(x):
  print(x)
  return x + "1"

letters = ["A", "B", "C"]
letters = map(prueba, letters)
print(list(letters))

A
B
C
['A1', 'B1', 'C1']

In [19]:
def prueba(x):
  print(x)
  dict_ = {}
  dict_[x["key"]] = x["key"] + "1"
  return dict_

letters = [{"key": "Z"}, {"key": "B"}, {"key": "C"}]
letters = map(prueba, letters)
print(list(letters))

{'key': 'Z'}
{'key': 'B'}
{'key': 'C'}
[{'Z': 'Z1'}, {'B': 'B1'}, {'C': 'C1'}]

___
### Map

`map()` is a built-in function that allows you to apply a function to each element of a sequence (such as a list or tuple) and return a new sequence of the results. The syntax for using `map()` is as follows:

```python
map(function, sequence)
```

Here, `function` is a function that takes one argument, and `sequence` is a sequence that can be iterated over (e.g. a list, tuple, or string). The `map()` function applies the given `function` to each element in the `sequence`, and returns a new sequence with the results.

<br>

#### Implementation

```python
  letters = ["A", "B", "C"]
  letters = map(str.lower, letters)
  print(list(letters))

  [out] ['a', 'b', 'c']
```

<br>

### Code examples

In [20]:
numbers = [1, 2, 3, 4, 5]
squared_numbers = list(map(lambda x: x**2, numbers))
print(squared_numbers)

<map object at 0x7fa585eae470>

In [21]:
celsius_temperatures = [0, 10, 20, 30, 40]
fahrenheit_temperatures = list(map(lambda x: (9/5)*x + 32, celsius_temperatures))
print(fahrenheit_temperatures)

(32.0, 50.0, 68.0, 86.0, 104.0)

In [ ]:
string_numbers = ['1', '2', '3', '4', '5']
int_numbers = list(map(int, string_numbers))
print(int_numbers)

[1, 2, 3, 4, 5]

In [ ]:
def double(num):
  return 2*num

numbers = [1, 2, 3, 4, 5]
numbers = list(map(double, numbers))
print(numbers)

[2, 4, 6, 8, 10]

___
### Filter

`filter()` function is used to filter out a sequence based on the given condition. It takes two arguments:

- A function that returns a Boolean value (`True` or `False`)
- A sequence that needs to be filtered.

The function is applied to each element in the sequence, and if it returns `True`, the element is included in the filtered result, otherwise, it is excluded.

Here's the syntax for the `filter()` function:

```python
filter(function, sequence)
```


where `function` is the function that returns `True` or `False` and `sequence` is the iterable that needs to be filtered.

The `filter()` function returns a filter object which can be converted to a list or tuple using the `list()` or `tuple()` function.

<br>

#### Implementation

```python
  def is_even(x):
      return x % 2 == 0

  numbers = [1, 2, 3, 4, 5, 6, 7, 8, 9, 10]
  even_numbers = filter(is_even, numbers)
  print(list(even_numbers))

  [out] [2, 4, 6, 8, 10]
```

<br>

### Code examples

In [ ]:
numbers = [1, 2, 3, 4, 5, 6, 7, 8, 9, 10]
even_numbers = filter(lambda x: x % 2 == 0, numbers)
print(list(even_numbers))

[2, 4, 6, 8, 10]

In [ ]:
words = ['apple', 'banana', 'cherry', 'date', 'elderberry', 'fig', 'chain']
c_words = list(filter(lambda x: x[0] == 'c', words))
print(c_words)

['cherry', 'chain']

In [ ]:
def is_prime(n):
    if n < 2:
        return False
    for i in range(2, int(n**0.5) + 1):
        if n % i == 0:
            return False
    return True

numbers = [1, 2, 3, 4, 5, 6, 7, 8, 9, 10]
prime_numbers = list(filter(is_prime, numbers))
print(prime_numbers)

[2, 3, 5, 7]

___
### Reduce

`reduce()` is a function from the `functools` module in Python that is used to apply a function to the elements of a sequence and reduce it to a single value. The function is applied cumulatively to the items in the sequence from left to right, so as to reduce the sequence to a single value.

The syntax for `reduce()` is as follows:

```python
reduce(function, sequence)
```

Here, `function` is the function to be applied to the elements of the `sequence`. `sequence` is the iterable that needs to be reduced.

<br>

#### Implementation

```python
  from functools import reduce

  numbers = [2, 3, 4, 5]
  product = reduce(lambda x, y: x * y, numbers)

  print(product)

  [out] 120
```

<br>

### Code examples

In [ ]:
from functools import reduce

In [ ]:
numbers = [2, 3, 4, 5]
addition = reduce(lambda x, y: x + y, numbers)
print(addition)

14

In [ ]:
numbers = [8, 3, 6, 1, 9, 2]
max_element = reduce(lambda x, y: x if x > y else y, numbers)
print(max_element)

9

In [ ]:
words = ["hello", "world", "how", "are", "you"]
concatenated_string = reduce(lambda x, y: x + " " + y, words)
print(concatenated_string)

hello world how are you

___
### Enumerate

`enumerate` is a built-in function that allows us to loop over an iterable object while keeping track of the index of each element. The `enumerate` function takes an iterable object as its argument and returns an iterator with tuples that contain two values: the index of the element and the element itself.

The syntax of the `enumerate` function is as follows:

```python
enumerate(iterable, start=0)
```

Here, `iterable` is the object that we want to iterate over, and `start` is an optional argument that specifies the starting index for the enumeration. By default, the starting index is `0`.

<br>

#### Implementation

```python
  fruits = ['apple', 'banana', 'orange']

  for i, fruit in enumerate(fruits):
      print(i, fruit)

  [out] 0 apple
        1 banana
        2 orange
```

<br>

### Code examples

In [26]:
students = ['John', 'Emily', 'Michael', 'Emma']

for i, name in enumerate(students):
    print(f"Student {i+1}: {name}")

Student 1: John
Student 2: Emily
Student 3: Michael
Student 4: Emma

In [27]:
fruits = ['apple', 'banana', 'orange', 'grape']
filtered_fruits = [fruit for index, fruit in enumerate(fruits) if index % 2 == 0]
print(filtered_fruits)

['apple', 'orange']

In [28]:
fruits = ['apple', 'banana', 'orange', 'grape']
fruit_dict = {index: fruit for index, fruit in enumerate(fruits)}
print(fruit_dict)

{0: 'apple', 1: 'banana', 2: 'orange', 3: 'grape'}

In [29]:
fruits = ['apple', 'banana', 'orange']
prices = [0.5, 0.25, 0.75]

for i, fruit in enumerate(fruits):
    price = prices[i]
    print(fruit, price)

apple 0.5
banana 0.25
orange 0.75

___
### Zip

`zip()` is a built-in Python function that allows you to combine two or more iterables into a single iterable object. It takes any number of iterables as input, and returns an iterator over tuples containing elements from each iterable.

When `zip()` is called on iterables with different lengths, it stops as soon as the shortest iterable is exhausted.

```python
zip(iterable1, iterable2, iterable3, ...)
```

Here, `iterable` is the object that we want to iterate over, and `start` is an optional argument that specifies the starting index for the enumeration. By default, the starting index is `0`.

<br>

#### Implementation

```python
  fruits = ['apple', 'banana', 'orange']
  prices = [1.0, 0.5, 0.75]

  for fruit, price in zip(fruits, prices):
      print(f"{fruit}: ${price}")

  [out] apple: $1.0
        banana: $0.5
        orange: $0.75
```

<br>

### Code examples

In [ ]:
list_name = ['John', 'Emily', 'Michael', 'Emma']
list_grade = [10, 9, 8.5, 9.5]

print("Student name: Grade")
for student, grade in zip(list_name, list_grade):
  print(f"{student}: {grade}")

Student name: Grade
John: 10
Emily: 9
Michael: 8.5
Emma: 9.5

In [ ]:
list_name = ['John', 'Emily', 'Michael', 'Emma']
list_grade = [10, 5, 6, 7]

print("Student name: Grade")
for student, grade in zip(list_name, list_grade):
  print(f"{student}: {'Fail' if grade < 6 else 'Pass'}")

Student name: Grade
John: Pass
Emily: Fail
Michael: Pass
Emma: Pass

In [ ]:
list_name = ['John', 'Emily', 'Michael', 'Emma']
list_grade = [10, 9, 8.5, 9.5]

student_dict = {student: grade for student, grade in zip(list_name, list_grade)}
print(student_dict)

{'John': 10, 'Emily': 9, 'Michael': 8.5, 'Emma': 9.5}

In [31]:
names = ["Alice", "Bob", "Charlie", "Dave"]
grades_math = [90, 80, 75, 85]
grades_science = [95, 85, 80, 90]
grades_english = [80, 75, 90, 95]

for name, math, science, english in zip(names, grades_math, grades_science, grades_english):
    print(f"{name}: Math={math}, Science={science}, English={english}")

Alice: Math=90, Science=95, English=80
Bob: Math=80, Science=85, English=75
Charlie: Math=75, Science=80, English=90
Dave: Math=85, Science=90, English=95

___
### Escape Characters

Escape characters are special characters that are used to represent characters that cannot be typed directly into a string or other text data type. They are used to add special formatting or functionality to strings. In Python, escape characters are preceded by a backslash (`\`). 

Some commonly used escape characters in Python include:

- `\n`: newline
- `\t`: tab
- `\\`: backslash
- `\'`: single quote
- `\"`: double quote

Here's an example:

```python
print("Hello\tworld!\nMy name is John\\Doe.")
```

This would output:

```
Hello   world!
My name is John\Doe.
```

In this example, the `\t` character inserts a tab between "Hello" and "world!", while the `\n` character inserts a newline between "world!" and "My". The `\\` character escapes the backslash, while the `\'` and `\"` characters escape single and double quotes, respectively.

<br>

### Code examples

In [ ]:
# Printing multiple lines using \n
print("Hello!\nHow are you?\nI hope you're doing well.")

Hello!
How are you?
I hope you're doing well.

In [ ]:
# Using \t to create an indented list
print("My favorite fruits are:\n\t- Apple\n\t- Banana\n\t- Orange")

My favorite fruits are:
	- Apple
	- Banana
	- Orange

In [ ]:
# Escaping the backslash character
print("This is a backslash: \\")

This is a backslash: \

In [ ]:
# Using single quotes inside a string
print("He said, 'Hello!'")
print('He said, \'Hello!\'')

print()
# Using double quotes inside a string
print('She said, "Hi there!"')
print("She said, \"Hi there!\"")

He said, 'Hello!'
He said, 'Hello!'

She said, "Hi there!"
She said, "Hi there!"

In [ ]:
# Using \u to display a Unicode character
print("\u00A9")  # Copyright symbol

# Using \U to display a Unicode character using 8 hexadecimal digits
print("\U0001F600")  # Grinning face emoji

©
😀

___
### Text files

Text files in Python are files containing text data, such as strings of characters. In Python, text files can be easily manipulated using file input/output (I/O) operations. Text files can be opened, read, written, and closed using built-in Python functions.

To open a text file, we use the built-in `open()` function. This function takes two arguments: the filename and the mode. The mode can be either "r" for reading, "w" for writing, "a" for appending, or "x" for creating a new file. When opening a file for reading or writing, it is important to close the file when you are finished with it, using the `close()` method.

Once the file is open, you can read or write to it using various methods, such as `read()`, `write()`, `readline()`, and `writelines()`. These methods allow you to read or write text data to or from the file.

<br>

#### Implementation

```python
# open the file for writing
f = open("file.txt", "w")

# write some text to the file
f.write("Hello, world!")

# close the file
f.close()
```

<br>

### Code examples

In [1]:
# open the file for writing
f = open("file.txt", "w")

# write some text to the file
f.write("Hello, world!")

# close the file
f.close()

In [15]:
# open the file for reading
f = open("file.txt", "r")

# read the contents of the file
contents = f.read()

# close the file
f.close()

# print the contents of the file
print(contents)

This is line 1
This is line 2
This is line 3

In [6]:
# List of lines to write to file
lines = ["This is line 1", "This is line 2", "This is line 3"]

# Open file for writing
file = open("example.txt", "w")

# Write lines to file
for text in lines:
  file.write(text)

# Close the file
file.close()

In [11]:
# List of lines to write to file
lines = ["This is line 1", "This is line 2", "This is line 3"]

# Open file for writing
file = open("example2.txt", "w")

# Write lines to file
file.writelines(lines)

# Close the file
file.close()

In [12]:
# Open file for reading
file = open("example.txt", "r")

# Read first line
line = file.readline()

# Loop through file and print out each line
while line:
    print(line)
    line = file.readline()

# Close the file
file.close()

This is line 1This is line 2This is line 3

In [13]:
# List of lines to write to file
lines = ["This is line 1\n", "This is line 2\n", "This is line 3\n"]

# Open file for writing
file = open("example_with_newlines.txt", "w")

# Write lines to file
file.writelines(lines)

# Close the file
file.close()

In [14]:
# Open file for reading
file = open("example_with_newlines.txt", "r")

# Read first line
line = file.readline()

# Loop through file and print out each line
while line:
    print(line, end="")
    line = file.readline()

# Close the file
file.close()

This is line 1
This is line 2
This is line 3